### ISSUE TITLE
Remove "" from Descr: in scenario's help message

### ISSUE THREAD

**Issue by skaluzka** [skaluzka/makbet#166]
## **makbet's version**
Please use below command to determine the version of **makbet** used:
```
makbet v0.3.0
```

## **Feature description**
Remove quotation marks (``""``) from ``Descr:`` in scenario's help message.

## **Expected solution**
In mentioned version all ``Descr:`` fields in help message are wrapped with ``""`` marks, as below:
```
  @01-INIT
    - Id.:   1
    - Descr: "Entry point"
    - Deps:  
    - Cmd:   
    - Opts: 
```

This could be changed, and unified (the ``""`` quotation marks should be removed), as below:
```
  @01-INIT
    - Id.:   1
    - Descr: Entry point
    - Deps:  
    - Cmd:   
    - Opts: 
```

## **Additional context**
N/A
